#!/usr/bin/bash

# Define the clock
Clock() {
        DATETIME=$(date "+%A, %d/%b/%Y %H:%M")

        echo -n "$DATETIME"
}

Mem() {
	USAGE=$(free --mega | awk 'NR==2 {printf("%.f"),$3}')
	TOTAL=$(free --giga | awk 'NR==2 {printf("%.f"),$2}')
	PERC=$(free -m | awk 'NR==2 {printf("%.f%"),$3/$2*100}')

	echo -n "$USAGE/$TOTAL $PERC"
}

# Print the clock
arg="$1"
Worspace(){
	WORK=$(leftwm-state -q -w $arg -t ~/.config/leftwm/themes/Mytheme/worspaces.liquid)
	echo -n "$WORK"
}

while true; do
	echo "%{l} $(Worspace) %{c} $(Mem) %{F-}%{B-} %{r} $(Clock) "
        sleep 0.1
done
