modkey = "Mod4"

mousekey = "Mod4"

workspaces = [
    { y = 0, x = 0, height = 1080, width = 1920, id = 0 },
    { y = 0, x = 1920, height = 900, width = 1600, id = 1 },
]

tags = ["", "", "ﱘ", "", ""]

layouts = ["MainAndVertStack", "MainAndHorizontalStack", "GridHorizontal", "EvenHorizontal", "EvenVertical", "CenterMainBalanced"]

layout_mode = "Workspace"

scratchpad = []

disable_current_tag_swap = true
focus_behaviour = "Sloppy"
focus_new_windows = true

keybind = [
# Execute
{command = "Execute", value = "alacritty", modifier = ["modkey"], key = "Return"},
{command = "Execute", value = "brave", modifier = ["modkey"], key = "b"},
{command = "Execute", value = "dmenu_run", modifier = ["modkey"], key = "p"},
{command = "Execute", value = "loginctl kill-session $XDG_SESSION_ID", modifier = ["modkey", "Shift"], key = "x"},
{command = "SoftReload", modifier = ["modkey", "Shift"], key = "r"},
{command = "HardReload", modifier = ["modkey", "Control"], key = "r"},

# Layout
{command = "NextLayout", modifier = ["modkey"], key = "F1"},

# Focus window
{command = "FocusWindowUp", modifier = ["modkey"], key = "k"},
{command = "FocusWindowDown", modifier = ["modkey"], key = "j"},

# Move window
{command = "MoveWindowUp", modifier = ["modkey", "Shift"], key = "k"},
{command = "MoveWindowDown", modifier = ["modkey", "Shift"], key = "j"},
{command = "MoveWindowTop", modifier = ["modkey"], key = "t"},

# Increase/Decrease window
{command = "CloseWindow", modifier = ["modkey"], key = "w"},
{command = "ToggleFullScreen", modifier = ["modkey"], key = "f"},
{command = "FloatingToTile", modifier = ["modkey", "Shift"], key = "t"},
{command = "TileToFloating", modifier = ["modkey", "Shift"], key = "f"},
{command = "IncreaseMainWidth", value = "5", modifier = ["modkey", "Control"], key = "h"},
{command = "DecreaseMainWidth", value = "5", modifier = ["modkey", "Control"], key = "l"},
{command = "SetMarginMultiplier", value = "1.0", modifier = ["modkey"], key = "m"},

# Go to tag
{command = "GotoTag", value = "1", modifier = ["modkey"], key = "1"},
{command = "GotoTag", value = "2", modifier = ["modkey"], key = "2"},
{command = "GotoTag", value = "3", modifier = ["modkey"], key = "3"},
{command = "GotoTag", value = "4", modifier = ["modkey"], key = "4"},
{command = "GotoTag", value = "5", modifier = ["modkey"], key = "5"},
{command = "GotoTag", value = "6", modifier = ["modkey"], key = "6"},

# Move to tag
{command = "MoveToTag", value = "1", modifier = ["modkey", "Shift"], key = "1"},
{command = "MoveToTag", value = "2", modifier = ["modkey", "Shift"], key = "2"},
{command = "MoveToTag", value = "3", modifier = ["modkey", "Shift"], key = "3"},
{command = "MoveToTag", value = "4", modifier = ["modkey", "Shift"], key = "4"},
{command = "MoveToTag", value = "5", modifier = ["modkey", "Shift"], key = "5"},
{command = "MoveToTag", value = "6", modifier = ["modkey", "Shift"], key = "6"},

{command = "SwapTags", modifier = ["modkey", "Shift"], key = "Tab"},
# Workspace
{command = "MoveWindowToNextWorkspace", modifier = ["modkey", "Shift"], key = "w"},
{command = "FocusWorkspaceNext", modifier = ["modkey"], key = "Tab"},

# Send Window to tag
{command = "Execute",value = "leftwm-command \"FocusWorkspaceNext\" \"FocusNextTag\" \"FocusWorkspacePrevious\"",modifier = ["modkey", "Control"],key = "Tab"},
]
