#!/bin/sh
export THEME="gruvbox"
export POLYBARTHEME="$THEME.config"

export MAINPATH="$( cd "$(dirname "$0")" || exit; pwd -P )"
export HWMON="$(fd . /sys/devices/platform/coretemp.0/hwmon/ | rg temp1_input)"
#export POLYBARTHEME="$MAINPATH/polybar/themes/"$THEME".config"
#export ROFITHEME="$MAINPATH/rofi/themes/"$THEME".config"

# Down the last running theme
if [ -f "/tmp/leftwm-theme-down" ]; then
    /tmp/leftwm-theme-down
    rm /tmp/leftwm-theme-down
fi
ln -s "$MAINPATH"/down /tmp/leftwm-theme-down

# Boot picom or compton if it exists
if [[ -x "$(command -v picom)" ]]; then
  picom --experimental-backends > /dev/null &
fi

# Set the theme.toml config
leftwm command "LoadTheme $MAINPATH/theme.toml"

# Set background
if [[ -x "$(command -v feh)" ]]; then
  feh --bg-fill "$MAINPATH"/background.png
fi

dunst &

index=0
leftwm-state -q -n -t "$MAINPATH"/sizes.liquid | sed -r '/^\s*$/d' | while read -r width
do
  barname="mainbar$index"
  monitor="$(polybar -m | awk -v i="$(( index + 1 ))" 'NR==i{print}' | sed s/:.*// | tr -d '\n')"
  monitor=$monitor width=$(( width - 16 )) polybar -c "$MAINPATH"/polybar/polybar.config $barname &
  index=$((index+1))
done
