#!/bin/bash

export MAINPATH
export HWMON   # used in polybar
export MONITOR # used in polybar
export INDEX=0 # sets leftwm-state -w, for polybar workspace module

MAINPATH="$(
	cd "$(dirname "$0")"
	pwd -P
)" || exit 1

get_hwmon_path() {
	HWMON="$(find /sys/devices/platform | grep -m 1 temp1_input)"
}

set_keyboard_rate() {
	xset r rate 200 50 &
}

unload_theme() {
	if [ -f "/tmp/leftwm-theme-down" ]; then
		/tmp/leftwm-theme-down
		rm /tmp/leftwm-theme-down
	fi
	ln -s "$MAINPATH"/down /tmp/leftwm-theme-down
}

load_theme() {
	unload_theme

	# Set the theme.toml config
	leftwm command "LoadTheme $MAINPATH/theme.ron" &
}

set_wallpaper() {
	if [ -x "$(command -v feh)" ]; then
		feh --bg-fill "$MAINPATH"/background.jpg &
	fi
}

compositor_init() {
	if [ -x "$(command -v picom)" ]; then
		pkill picom
		picom &
	fi
}

polybar_init() {
	pkill polybar
	cfg="$HOME"/.config/polybar/polybar.ini
	for m in $(polybar -m | sed 's/:.*//'); do
		MONITOR="$m" polybar -c "$cfg" main"$INDEX" &
		((INDEX += 1))
	done
}

set_keyboard_rate
compositor_init
set_wallpaper
get_hwmon_path
load_theme
polybar_init
